<a href="https://colab.research.google.com/github/martha-rincon-lopez/Proyectos/blob/main/Ejercicios_R_Cap%C3%ADtulo_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Ejercicios R**

# **Capítulo 2: Tipos de Objetos**

1. Construya un vector con la primeras 20 letras MAYÚSCULAS usando la función LETTERS.

In [ ]:
x<-toupper(c(letters[1:20]))
x

[1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T"

2. Construya una matriz de 10 x 10 con los primeros 100 números positivos pares.


In [ ]:
num.par.matriz <- 0 #contador de número pares para la matriz
num.par <- -2   #contador de pares obtenidos
historial<-NULL  #vector vacío para almacenar

while (num.par.matriz < 101){
  num.par <- num.par + 1
  historial[num.par.matriz] <- num.par
  if(num.par %% 2 == 0){
    num.par.matriz <- num.par.matriz + 1
  }
}
#historial
matriz1<-matrix(data=historial, nrow=10, ncol=10, byrow=FALSE)
matriz1

[,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]  2   22   42   62    82  102  122  142  162  182  
 [2,]  4   24   44   64    84  104  124  144  164  184  
 [3,]  6   26   46   66    86  106  126  146  166  186  
 [4,]  8   28   48   68    88  108  128  148  168  188  
 [5,] 10   30   50   70    90  110  130  150  170  190  
 [6,] 12   32   52   72    92  112  132  152  172  192  
 [7,] 14   34   54   74    94  114  134  154  174  194  
 [8,] 16   36   56   76    96  116  136  156  176  196  
 [9,] 18   38   58   78    98  118  138  158  178  198  
[10,] 20   40   60   80   100  120  140  160  180  200

3. Construya una matriz identidad de dimension 3 x 3. Recuerde que una matriz identidad tiene sólo unos en la diagonal principal y los demás elementos son cero.

In [ ]:
valor<- c(1,0,0,0,1,0,0,0,1) #Opciones de elementos en la matriz
matriz2<- matrix(data = valor, nrow = 3, ncol = 3, byrow = FALSE)
matriz2

[,1] [,2] [,3]
[1,] 1    0    0   
[2,] 0    1    0   
[3,] 0    0    1

4. Construya una lista con los anteriores tres objetos creados.

In [ ]:
milista<- list(E1 = x, E2 = matriz1, E3 = matriz2)
milista

$E1
 [1] "A" "B" "C" "D" "E" "F" "G" "H" "I" "J" "K" "L" "M" "N" "O" "P" "Q" "R" "S"
[20] "T"

$E2
      [,1] [,2] [,3] [,4] [,5] [,6] [,7] [,8] [,9] [,10]
 [1,]    2   22   42   62   82  102  122  142  162   182
 [2,]    4   24   44   64   84  104  124  144  164   184
 [3,]    6   26   46   66   86  106  126  146  166   186
 [4,]    8   28   48   68   88  108  128  148  168   188
 [5,]   10   30   50   70   90  110  130  150  170   190
 [6,]   12   32   52   72   92  112  132  152  172   192
 [7,]   14   34   54   74   94  114  134  154  174   194
 [8,]   16   36   56   76   96  116  136  156  176   196
 [9,]   18   38   58   78   98  118  138  158  178   198
[10,]   20   40   60   80  100  120  140  160  180   200

$E3
     [,1] [,2] [,3]
[1,]    1    0    0
[2,]    0    1    0
[3,]    0    0    1

5. Construya un marco de datos o data frame con las respuestas de 3 personas a las preguntas:
(a) ¿Cuál es su edad en años?
(b) ¿Tipo de música que más le gusta? (c) ¿Tiene usted pareja sentimental estable?

In [ ]:
edad <- c(10, 15, 21)
music_fav <-c('pop', 'rock', 'clasica')
pareja <- c('TRUE','FALSE', 'TRUE')
mimarco_1 <- data.frame(edad, music_fav, pareja)
mimarco_1

edad music_fav pareja
1 10   pop       TRUE  
2 15   rock      FALSE 
3 21   clasica   TRUE

6. ¿Cuál es el error al correr el siguiente código? ¿A qué se debe?

      No podemos crear una matriz con esos datos, no es numérica

In [ ]:
edad <- c(15, 19, 13, NA, 20)
deporte <- c(TRUE, TRUE, NA, FALSE, TRUE)
comic_fav <- c(NA, 'Superman', 'Batman', NA, 'Batman')
matrix(edad, deporte, comic_fav)

ERROR: ignored